# Generated by Django 5.2.15 on 2026-07-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('caller_class', models.CharField(db_index=True, max_length=40)),
                ('outcome', models.CharField(db_index=True, max_length=20)),
                ('duration_ms', models.PositiveIntegerField()),
                ('freshness_status', models.CharField(default='unknown', max_length=20)),
                ('freshness_as_of', models.CharField(blank=True, max_length=80)),
                ('error_class', models.CharField(blank=True, max_length=120)),
                ('called_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-called_at'],
                'indexes': [models.Index(fields=['tool_name', 'called_at'], name='mcp_tool_time_idx')],
            },
        ),
    ]
