# Generated by Django 5.2.15 on 2026-07-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFRDatasetBuildRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.TextField(default='success')),
                ('error', models.TextField(blank=True)),
                ('dataset_version', models.TextField(default='prototype_current_characteristics')),
                ('total_sales_loaded', models.IntegerField(null=True)),
                ('retained_sfr_sales', models.IntegerField(null=True)),
                ('excluded_by_reason', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'sfr_dataset_build_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SFRRatioStudyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.TextField(default='success')),
                ('error', models.TextField(blank=True)),
                ('recent_years', models.IntegerField(null=True)),
                ('window_start_year', models.IntegerField(null=True)),
                ('window_end_year', models.IntegerField(null=True)),
                ('train_count', models.IntegerField(null=True)),
                ('test_count', models.IntegerField(null=True)),
                ('primary_model', models.TextField(blank=True)),
                ('model_comparison', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'sfr_ratio_study_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
