# Generated by Django 5.2.15 on 2026-07-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0002_sfrdatasetbuildrun_sfrratiostudyrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFRComplianceLoopRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.TextField(default='success')),
                ('error', models.TextField(blank=True)),
                ('segments_attempted', models.IntegerField(null=True)),
                ('segments_compliant', models.IntegerField(null=True)),
                ('segments_provisional', models.IntegerField(null=True)),
                ('segments_dropped', models.IntegerField(null=True)),
                ('ai_calls_made', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sfr_compliance_loop_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='modelsfrsalesdataset',
            name='zoning_general_category',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='SFRSegmentExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_value', models.TextField()),
                ('attempt_kind', models.TextField()),
                ('attempt_number', models.IntegerField()),
                ('train_count', models.IntegerField(null=True)),
                ('test_count', models.IntegerField(null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('passed', models.BooleanField(default=False)),
                ('coefficients', models.JSONField(blank=True, null=True)),
                ('ai_rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sfr_segment_experiments',
                'ordering': ['segment_value', 'attempt_number'],
                'indexes': [models.Index(fields=['segment_value'], name='sfr_segment_segment_7bd09a_idx'), models.Index(fields=['attempt_kind'], name='sfr_segment_attempt_f655bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SFRSegmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_value', models.TextField(unique=True)),
                ('model_name', models.TextField(blank=True)),
                ('coefficients', models.JSONField(blank=True, null=True)),
                ('feature_medians', models.JSONField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('sample_count', models.IntegerField(null=True)),
                ('status', models.TextField(choices=[('compliant', 'Compliant'), ('provisional', 'Provisional'), ('dropped', 'Dropped')])),
                ('recommendation', models.TextField(blank=True)),
                ('attempts_made', models.IntegerField(default=0)),
                ('trained_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sfr_segment_models',
                'ordering': ['segment_value'],
                'indexes': [models.Index(fields=['status'], name='sfr_segment_status_5578c3_idx')],
            },
        ),
    ]
