# Generated by Django 5.2.15 on 2026-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0003_sfrcompliancelooprun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfrcompliancelooprun',
            name='recent_years',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sfrcompliancelooprun',
            name='segment_scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sfrcompliancelooprun',
            name='window_end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sfrcompliancelooprun',
            name='window_start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sfrcompliancelooprun',
            name='status',
            field=models.TextField(default='running'),
        ),
    ]
