# Generated by Django 5.2.15 on 2026-07-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphEntity',
            fields=[
                ('entity_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('canonical_name', models.TextField()),
                ('kind', models.CharField(default='unknown', max_length=16)),
                ('raw_name_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'graph_entities',
                'indexes': [models.Index(fields=['kind'], name='graph_entity_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='GraphEntityParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=64)),
                ('parcel_number', models.TextField()),
                ('source', models.CharField(default='assessor', max_length=32)),
            ],
            options={
                'db_table': 'graph_entity_parcels',
                'indexes': [models.Index(fields=['parcel_number'], name='graph_entity_parcel_pid_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_id', 'parcel_number', 'source'), name='graph_entity_parcel_unique')],
            },
        ),
        migrations.CreateModel(
            name='GraphOwnershipGroup',
            fields=[
                ('group_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('member_entity_ids', models.JSONField(default=list)),
                ('link_reason', models.CharField(max_length=40)),
                ('mailing_key', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'graph_ownership_groups',
                'indexes': [models.Index(fields=['link_reason'], name='graph_group_reason_idx')],
            },
        ),
    ]
