# Generated by Django 5.2.15 on 2026-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphBuildState',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'graph_build_state',
            },
        ),
        migrations.CreateModel(
            name='GraphParcelAdjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid_a', models.TextField()),
                ('pid_b', models.TextField()),
                ('shared_boundary_ft', models.FloatField()),
            ],
            options={
                'db_table': 'graph_parcel_adjacency',
                'indexes': [models.Index(fields=['pid_a'], name='graph_adjacency_a_idx'), models.Index(fields=['pid_b'], name='graph_adjacency_b_idx')],
                'constraints': [models.UniqueConstraint(fields=('pid_a', 'pid_b'), name='graph_adjacency_pair_unique')],
            },
        ),
    ]
