# Generated by Django 5.2.15 on 2026-06-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessor_sync', '__first__'),
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelBookSyncNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(blank=True)),
                ('headline', models.TextField()),
                ('narrative', models.TextField()),
                ('bullets', models.JSONField(default=list)),
                ('summary_snapshot', models.JSONField(default=dict)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor_sync_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_book_narrative', to='assessor_sync.assessorsyncreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='opportunity_created_26f68c_idx'), models.Index(fields=['generated_by_ai', '-created_at'], name='opportunity_generat_08c9f4_idx')],
            },
        ),
    ]
