# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0004_opportunitysearch_plan_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcelbooksyncnarrative",
            name="brief_context",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="parcelbooksyncnarrative",
            name="dek",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="parcelbooksyncnarrative",
            name="disclaimer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="parcelbooksyncnarrative",
            name="newsletter_subject",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="parcelbooksyncnarrative",
            name="notable_signals",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="parcelbooksyncnarrative",
            name="preview_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="parcelbooksyncnarrative",
            name="trend_line",
            field=models.TextField(blank=True),
        ),
    ]
