# Generated by Django 5.2.15 on 2026-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_public_intelligence_index_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitysearch',
            name='query_language',
            field=models.CharField(default='sql', max_length=16),
        ),
    ]
