# Generated by Django 5.2.15 on 2026-07-06 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxtool', '0002_parcelsearchcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxShiftEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('taxshift_watchlist_digest', 'TaxShift watchlist digest')], max_length=32, unique=True)),
                ('subject', models.TextField()),
                ('body_html', models.TextField(help_text='Django template syntax. Variables: {{ signup }}, {{ changes }}, {{ unsubscribe_url }}, {{ site_url }}.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxShiftNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.TextField()),
                ('trigger_type', models.CharField(choices=[('assessor_change', 'Assessor data change'), ('auditor_recording', 'Auditor recording')], max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('run_id', models.BigIntegerField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taxshiftsignup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxshiftsignup',
            name='parcel_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taxshiftsignup',
            name='recorded_docs_snapshot',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='taxshiftsignup',
            name='resolution_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('ambiguous', 'Ambiguous')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='taxshiftsignup',
            name='snapshot_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxshiftsignup',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='taxshiftsignup',
            index=models.Index(fields=['parcel_number'], name='taxtool_signup_parcel_idx'),
        ),
        migrations.AddIndex(
            model_name='taxshiftsignup',
            index=models.Index(fields=['resolution_status'], name='taxtool_signup_status_idx'),
        ),
        migrations.AddField(
            model_name='taxshiftnotification',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='taxtool.taxshiftsignup'),
        ),
        migrations.AddIndex(
            model_name='taxshiftnotification',
            index=models.Index(fields=['signup', 'sent_at', '-created_at'], name='taxtool_notif_signup_idx'),
        ),
        migrations.AddIndex(
            model_name='taxshiftnotification',
            index=models.Index(fields=['trigger_type', 'sent_at'], name='taxtool_notif_trigger_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxshiftnotification',
            constraint=models.UniqueConstraint(fields=('signup', 'parcel_number', 'trigger_type', 'run_id'), name='uniq_taxshift_notification'),
        ),
    ]
