# Generated by Django 5.2.15 on 2026-07-06 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxtool', '0003_taxshiftemailtemplate_taxshiftnotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxshiftsignup',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxshiftsignup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxshift_signups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxshiftsignup',
            name='verification_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxshiftsignup',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxshiftemailtemplate',
            name='body_html',
            field=models.TextField(help_text='Django template syntax. Watchlist digest variables: {{ signup }}, {{ changes }}, {{ unsubscribe_url }}, {{ site_url }}. Verification variables: {{ signup }}, {{ snapshot }}, {{ verify_url }}, {{ unsubscribe_url }}, {{ parcel_url }}, {{ site_url }}.'),
        ),
        migrations.AlterField(
            model_name='taxshiftemailtemplate',
            name='name',
            field=models.CharField(choices=[('taxshift_watchlist_digest', 'TaxShift watchlist digest'), ('taxshift_verification', 'TaxShift verification + snapshot summary')], max_length=32, unique=True),
        ),
    ]
