# Generated by Django 5.2.16 on 2026-07-30 17:16

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=150)),
                ("vendor_name", models.CharField(max_length=150)),
                ("vendor_email", models.EmailField(blank=True, max_length=254)),
                ("requested_unit", models.CharField(default="each", max_length=50)),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_archived", models.BooleanField(default=False)),
                ("traffic", models.PositiveIntegerField(default=10000)),
                (
                    "capture_rate",
                    models.DecimalField(decimal_places=4, default=0.1, max_digits=6),
                ),
                ("operating_days", models.PositiveSmallIntegerField(default=20)),
                (
                    "hours_per_day",
                    models.DecimalField(decimal_places=2, default=9, max_digits=5),
                ),
                ("max_transactions_per_hour", models.PositiveIntegerField(default=150)),
                (
                    "sales_tax_rate",
                    models.DecimalField(decimal_places=4, default=0.087, max_digits=6),
                ),
                (
                    "sales_tax_treatment",
                    models.CharField(
                        choices=[
                            ("included", "Included in prices"),
                            ("added", "Added at checkout"),
                        ],
                        default="included",
                        max_length=10,
                    ),
                ),
                (
                    "waste_rate",
                    models.DecimalField(decimal_places=4, default=0.05, max_digits=6),
                ),
                (
                    "card_rate",
                    models.DecimalField(decimal_places=4, default=0.029, max_digits=6),
                ),
                (
                    "card_fixed_fee",
                    models.DecimalField(decimal_places=2, default=0.3, max_digits=6),
                ),
                (
                    "fixed_costs",
                    models.DecimalField(decimal_places=2, default=22600, max_digits=12),
                ),
                (
                    "operating_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livefire_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_archived", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("addon", "Add-on")],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("food_cost", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "packaging_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("purchase_rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("vendor", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="livefire.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="livefire.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DayAssumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("traffic", models.PositiveIntegerField(default=10000)),
                (
                    "capture_rate",
                    models.DecimalField(decimal_places=4, default=0.1, max_digits=6),
                ),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=9, max_digits=5),
                ),
                ("occurrences", models.PositiveSmallIntegerField(default=5)),
                ("max_transactions_per_hour", models.PositiveIntegerField(default=150)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="livefire.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("data", models.JSONField()),
                ("visible_sections", models.JSONField(default=list)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="livefire.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("employee_count", models.PositiveSmallIntegerField(default=1)),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("wage", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "payroll_burden",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffing",
                        to="livefire.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "package_size",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                (
                    "minimum_order",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("available", models.BooleanField(default=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("preferred", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="livefire.quoterequest",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_livefire_scenario_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="dayassumption",
            constraint=models.UniqueConstraint(
                fields=("scenario", "day"), name="unique_livefire_scenario_day"
            ),
        ),
    ]
