# Generated by Django 5.2.16 on 2026-07-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livefire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayassumption",
            name="capture_rate",
            field=models.DecimalField(decimal_places=4, default="0.10", max_digits=6),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="capture_rate",
            field=models.DecimalField(decimal_places=4, default="0.10", max_digits=6),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="card_fixed_fee",
            field=models.DecimalField(decimal_places=2, default="0.30", max_digits=6),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="card_rate",
            field=models.DecimalField(decimal_places=4, default="0.029", max_digits=6),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="sales_tax_rate",
            field=models.DecimalField(decimal_places=4, default="0.087", max_digits=6),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="waste_rate",
            field=models.DecimalField(decimal_places=4, default="0.05", max_digits=6),
        ),
    ]
