# Generated by Codex on 2026-06-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                ("code_source", models.CharField(blank=True, max_length=160)),
                ("zoning_title", models.CharField(blank=True, max_length=240)),
                ("source_url", models.URLField(blank=True)),
                ("extraction_status", models.CharField(blank=True, max_length=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["display_name"]},
        ),
        migrations.CreateModel(
            name="ZoningCodeDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=240)),
                ("chapter", models.CharField(blank=True, max_length=120)),
                ("source_url", models.URLField(unique=True)),
                ("text", models.TextField(blank=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("jurisdiction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="code_documents", to="zoning_mcp.jurisdiction")),
            ],
            options={"ordering": ["jurisdiction__display_name", "chapter", "title"]},
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zone_code", models.CharField(max_length=40)),
                ("zone_name", models.CharField(blank=True, max_length=240)),
                ("source_url", models.URLField(blank=True)),
                ("jurisdiction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="zones", to="zoning_mcp.jurisdiction")),
            ],
            options={"ordering": ["jurisdiction__display_name", "zone_code"], "unique_together": {("jurisdiction", "zone_code")}},
        ),
        migrations.CreateModel(
            name="ZoningUseRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("use_category", models.CharField(blank=True, max_length=160)),
                ("use_name", models.CharField(max_length=240)),
                ("normalized_use_key", models.SlugField(max_length=180)),
                ("local_status", models.CharField(choices=[("P", "Permitted"), ("AC", "Accessory"), ("AD", "Administrative Review"), ("HE", "Hearing Examiner"), ("C", "Conditional"), ("CUP", "Conditional Use Permit"), ("X", "Prohibited"), ("UNKNOWN", "Unknown / Not Parsed")], max_length=20)),
                ("normalized_status", models.CharField(choices=[("P", "Permitted"), ("AC", "Accessory"), ("AD", "Administrative Review"), ("HE", "Hearing Examiner"), ("C", "Conditional"), ("CUP", "Conditional Use Permit"), ("X", "Prohibited"), ("UNKNOWN", "Unknown / Not Parsed")], max_length=20)),
                ("source_table", models.CharField(blank=True, max_length=240)),
                ("source_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jurisdiction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="use_rules", to="zoning_mcp.jurisdiction")),
                ("zone", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="use_rules", to="zoning_mcp.zone")),
            ],
            options={"ordering": ["jurisdiction__display_name", "zone__zone_code", "use_category", "use_name"], "unique_together": {("jurisdiction", "zone", "normalized_use_key", "source_table")}},
        ),
        migrations.AddIndex(model_name="zoninguserule", index=models.Index(fields=["jurisdiction", "zone", "normalized_use_key"], name="zoning_mcp__jurisdi_b1c8f8_idx")),
        migrations.AddIndex(model_name="zoninguserule", index=models.Index(fields=["jurisdiction", "normalized_use_key", "normalized_status"], name="zoning_mcp__jurisdi_6ea30b_idx")),
    ]
