# Generated by Django 5.2.15 on 2026-06-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoning_mcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoningCodeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('chapter_ref', models.CharField(max_length=120)),
                ('chapter_title', models.CharField(max_length=240)),
                ('section', models.CharField(max_length=40)),
                ('heading', models.CharField(max_length=300)),
                ('text', models.TextField(blank=True)),
                ('source_url', models.URLField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_sections', to='zoning_mcp.jurisdiction')),
            ],
            options={
                'ordering': ['jurisdiction__display_name', 'chapter_ref', 'order'],
                'indexes': [models.Index(fields=['jurisdiction', 'section'], name='zoning_mcp__jurisdi_0af040_idx'), models.Index(fields=['jurisdiction', 'chapter_ref', 'order'], name='zoning_mcp__jurisdi_abd62c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ZoningSourceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('chapter_ref', models.CharField(max_length=120)),
                ('chapter_title', models.CharField(max_length=240)),
                ('table_index', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('nearest_heading', models.CharField(blank=True, max_length=300)),
                ('source_url', models.URLField()),
                ('rows', models.JSONField(default=list)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tables', to='zoning_mcp.jurisdiction')),
            ],
            options={
                'ordering': ['jurisdiction__display_name', 'chapter_ref', 'table_index'],
                'indexes': [models.Index(fields=['jurisdiction', 'caption'], name='zoning_mcp__jurisdi_1c9a05_idx'), models.Index(fields=['jurisdiction', 'chapter_ref', 'table_index'], name='zoning_mcp__jurisdi_84ebca_idx')],
                'unique_together': {('jurisdiction', 'chapter_ref', 'table_index')},
            },
        ),
    ]
