# Generated by Django 5.2.15 on 2026-07-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessor_sync', '0001_live_check_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GISSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.TextField(unique=True)),
                ('display_name', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('expected_geometry_type', models.TextField(blank=True)),
                ('refresh_frequency', models.TextField(blank=True)),
                ('raw_file_path', models.TextField(blank=True)),
                ('extracted_path', models.TextField(blank=True)),
                ('source_hash', models.TextField(blank=True)),
                ('previous_source_hash', models.TextField(blank=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.TextField(default='never_synced')),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gis_sources',
                'ordering': ['layer_name'],
            },
        ),
    ]
