# Generated by Django 5.2.15 on 2026-07-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessor_sync', '0002_gissource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelGeoStaticFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.TextField(unique=True)),
                ('prop_id', models.TextField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('point_source', models.TextField(blank=True, null=True)),
                ('city_name', models.TextField(blank=True, null=True)),
                ('comp_plan_designation', models.TextField(blank=True, null=True)),
                ('school_district', models.TextField(blank=True, null=True)),
                ('fire_district', models.TextField(blank=True, null=True)),
                ('voting_precinct', models.TextField(blank=True, null=True)),
                ('historical_area_flag', models.BooleanField(default=False)),
                ('nearest_road_name', models.TextField(blank=True, null=True)),
                ('distance_to_nearest_road_feet', models.FloatField(blank=True, null=True)),
                ('distance_to_nearest_road_miles', models.FloatField(blank=True, null=True)),
                ('distance_to_mount_vernon_miles', models.FloatField(blank=True, null=True)),
                ('distance_to_burlington_miles', models.FloatField(blank=True, null=True)),
                ('distance_to_sedro_woolley_miles', models.FloatField(blank=True, null=True)),
                ('distance_to_anacortes_miles', models.FloatField(blank=True, null=True)),
                ('distance_to_la_conner_miles', models.FloatField(blank=True, null=True)),
                ('nearest_public_place_name', models.TextField(blank=True, null=True)),
                ('distance_to_nearest_public_place_miles', models.FloatField(blank=True, null=True)),
                ('distance_to_nearest_tide_gate_miles', models.FloatField(blank=True, null=True)),
                ('missing_coordinate_flag', models.BooleanField(default=False)),
                ('feature_status', models.TextField(default='ok')),
                ('feature_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parcel_geo_static_features',
                'ordering': ['parcel_number'],
                'indexes': [models.Index(fields=['feature_status'], name='parcel_geo__feature_5a660c_idx')],
            },
        ),
    ]
