# Generated by Django 5.2.15 on 2026-06-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxStatementRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('backfill', 'Backfill'), ('slow_check', 'Slow check'), ('single', 'Single parcel')], max_length=24)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('stopped', 'Stopped')], default='running', max_length=24)),
                ('years', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('parcels_considered', models.IntegerField(default=0)),
                ('statements_attempted', models.IntegerField(default=0)),
                ('statements_saved', models.IntegerField(default=0)),
                ('statements_skipped', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxStatementError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.TextField(db_index=True)),
                ('tax_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('source_url', models.TextField(blank=True)),
                ('error_type', models.TextField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax_delinquency.taxstatementrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved_at', 'created_at'], name='tax_delinqu_resolve_7eda8f_idx'), models.Index(fields=['parcel_number', 'tax_year'], name='tax_delinqu_parcel__7a0f0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.TextField(db_index=True)),
                ('tax_account_number', models.TextField(blank=True, db_index=True, null=True)),
                ('tax_year', models.IntegerField(db_index=True)),
                ('owner_name', models.TextField(blank=True, null=True)),
                ('situs_address', models.TextField(blank=True, null=True)),
                ('levy_code', models.TextField(blank=True, null=True)),
                ('general_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_assessments_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid')], default='unknown', max_length=24)),
                ('lead_level', models.CharField(choices=[('clear', 'Clear'), ('watch', 'Watch'), ('one_late', 'One late'), ('behind', 'Behind'), ('serious', 'Serious'), ('severe', 'Severe'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=24)),
                ('delinquent_installment_count', models.IntegerField(default=0)),
                ('unpaid_installment_count', models.IntegerField(default=0)),
                ('oldest_due_date', models.DateField(blank=True, null=True)),
                ('source_url', models.TextField()),
                ('source_fetched_at', models.DateTimeField(db_index=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax_delinquency.taxstatementrun')),
            ],
            options={
                'indexes': [models.Index(fields=['lead_level', 'total_due'], name='tax_delinqu_lead_le_a6f7f4_idx'), models.Index(fields=['source_fetched_at', 'parcel_number'], name='tax_delinqu_source__5d41eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('parcel_number', 'tax_year'), name='uniq_tax_statement_parcel_year')],
            },
        ),
    ]
