# Generated by Django 5.2.15 on 2026-06-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_delinquency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxStatementCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.TextField(db_index=True)),
                ('tax_year', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid')], default='unknown', max_length=24)),
                ('total_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_fetched_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax_delinquency.taxstatementrun')),
            ],
            options={
                'indexes': [models.Index(fields=['source_fetched_at', 'parcel_number'], name='tax_delinqu_source__bfaa04_idx')],
                'constraints': [models.UniqueConstraint(fields=('parcel_number', 'tax_year'), name='uniq_tax_statement_check_parcel_year')],
            },
        ),
    ]
