# Generated by Django 5.2.15 on 2026-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlineitem',
            name='category_name',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='is_total',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='scope',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='source_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='budgetlineitem',
            index=models.Index(fields=['document', 'reviewed', 'is_total'], name='budgets_bud_documen_a96be6_idx'),
        ),
    ]
