# Generated by Django 5.2.16 on 2026-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_budgetlineitem_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetjurisdiction",
            name="population",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budgetjurisdiction",
            name="population_source",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="budgetjurisdiction",
            name="population_source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="budgetjurisdiction",
            name="population_source_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
